version: "3.9"
services:
#    scripts:
#        build: ./docker/laravel_scripts/
#        volumes:
#            - .:/app
#        container_name: script
#        networks:
#            - app-network
#        depends_on:
#            - app_database
#            - laravel_app

    app_database:
        image: mysql
        networks:
            - app-network
        environment:
            - MYSQL_ROOT_PASSWORD=natan
        ports:
            - 2000:3306
        container_name: laravel_database

    laravel_app:
        build: .
        networks:
            - app-network
        container_name: laravel_app
        volumes:
            - .:/app
        ports:
            - 3000:8000
        depends_on:
            - app_database
networks:
    app-network:
        driver: bridge
