version: "3.9"
services:
    app_database:
        image: mysql
        networks:
            - app
        environment:
            - MYSQL_ROOT_PASSWORD=natan
        ports:
            - 2000:3306
        container_name: laravel_database

    laravel_app:
        build: .
        networks:
            - app
        container_name: laravel_app
        volumes:
            - .:/app
        ports:
            - 3000:8000
networks:
    app:
        driver: bridge
